# Generated by Django 3.0.6 on 2020-06-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_abstract'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(default='', verbose_name='../static/images/newsimages'),
        ),
    ]
