# Generated by Django 3.0.6 on 2020-06-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200611_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.URLField(default='', verbose_name='image'),
        ),
    ]
