# Generated by Django 3.0.6 on 2020-06-24 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20200624_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
    ]
