# Generated by Django 3.0.6 on 2020-07-01 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20200624_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
    ]
