# Generated by Django 2.2.2 on 2019-06-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BabyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(default='男', max_length=2)),
                ('birthtime', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='NoteRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=5)),
                ('record', models.CharField(max_length=150)),
            ],
        ),
    ]
