# Generated by Django 2.2.2 on 2019-06-15 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_auto_20190615_0628'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='babyinfo',
        ),
    ]
